# Generated by Django 5.0.4 on 2024-04-18 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_orderitem_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(max_length=100),
        ),
    ]
