# Generated by Django 5.0.4 on 2024-04-18 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_order_order_date_remove_order_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
